export const IPC = {
  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',
  ProvidersList: 'providers:list',
  ProviderUpsert: 'providers:upsert',
  ProviderDelete: 'providers:delete',
  ProviderTest: 'providers:test',
  ConversationsList: 'conversations:list',
  ConversationGet: 'conversations:get',
  ConversationUpsert: 'conversations:upsert',
  ConversationDelete: 'conversations:delete',
  MemoriesList: 'memories:list',
  MemoryUpsert: 'memories:upsert',
  MemoryDelete: 'memories:delete',
  MemoriesSearch: 'memories:search',
  ConnectorsList: 'connectors:list',
  ConnectorSave: 'connectors:save',
  ConnectorAuthStart: 'connectors:auth:start',
  ConnectorAuthStatus: 'connectors:auth:status',
  ConnectorConnect: 'connectors:connect',
  ConnectorDisconnect: 'connectors:disconnect',
  ConnectorBrowserSetup: 'connectors:browser:setup',
  ConnectorActivities: 'connectors:activities',
  ConnectorMessageSend: 'connectors:message:send',
  ChatStart: 'chat:start',
  ChatCancel: 'chat:cancel',
  ChatChunk: 'chat:chunk',
  AgentStart: 'agent:start',
  AgentCancel: 'agent:cancel',
  AgentApprove: 'agent:approve',
  AgentChunk: 'agent:chunk',
  AgentPickDirectory: 'agent:pick-directory',
  AgentSessionsList: 'agent:sessions:list',
  AgentSessionUpsert: 'agent:sessions:upsert',
  AgentSessionDelete: 'agent:sessions:delete',
  AgentSessionRename: 'agent:sessions:rename',
  WindowMinimize: 'window:minimize',
  WindowToggleMaximize: 'window:toggle-maximize',
  WindowClose: 'window:close',
  WindowIsMaximized: 'window:is-maximized',
  WindowMaximizedChanged: 'window:maximized-changed',
  OpenExternal: 'app:open-external',
  AppVersion: 'app:version'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
